### ISSUE TITLE
mixerpreset script missing

### ISSUE THREAD

**Issue by dddesign** [v0d0r/volumio-hacks#1]
found your blogpost here http://www.opennet.za.net/e107/e107_plugins/content/content.php?content.12
there you mention the mixerpreset script, but I can't find these here. Can you upload this or where can I find it?
j

**Comment by v0d0r** [comment]
All my files are checked in on github.

https://github.com/v0d0r/volumio-hacks

On 18/06/2015 21:57, jan gloeckner wrote:

> found your blogpost here 
> http://www.opennet.za.net/e107/e107_plugins/content/content.php?content.12
> there you mention the mixerpreset script, but I can't find these here. 
> Can you upload this or where can I find it?
> j
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/v0d0r/volumio-hacks/issues/1.

## 

Kevin

**Comment by dddesign** [comment]
can't find the bash script mixerpreset. do I miss something?!

**Comment by v0d0r** [comment]
Nope your right sorry. It's missing for some reason.

Once I get home I will mail you a copy and push to github also.

On 18/06/2015 22:21, jan gloeckner wrote:

> can't find the bash script mixerpreset. do I miss something?!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/v0d0r/volumio-hacks/issues/1#issuecomment-113278684.

## 

Kevin

**Comment by dddesign** [comment]
perfect

**Comment by v0d0r** [comment]
Nevermind ignore the previous email. Turns out I could SSH to my volumio 
host from here.
Below is the content of the mixerpreset script.

---

set_equalizer_curve() {
   curve="${*}"
   ctl=0
   for point in ${curve}
   do
     ctl=$(( ${ctl} + 1 ))
     echo cset numid=${ctl} ${point}
   done | amixer -D equal -s
}

profile="${1:-flat}"
case "${profile}" in
flat) curve="65 65 65 65 65 65 65 65 65 65" ;;
classical) curve="71 71 71 71 71 71 84 83 83 87" ;;
club) curve="71 71 67 63 63 63 67 71 71 71" ;;
dance) curve="57 61 69 71 71 81 83 83 71 71" ;;
headphones) curve="65 55 64 77 75 70 65 57 52 49" ;;
bass) curve="59 59 59 63 70 78 85 88 89 89" ;;
treble) curve="87 87 87 78 68 55 47 47 47 45" ;;
large_hall) curve="56 56 63 63 71 79 79 79 71 71" ;;
live) curve="79 71 66 64 63 63 66 68 68 69" ;;
party) curve="61 61 71 71 71 71 71 71 61 61" ;;
pop) curve="74 65 61 60 64 73 75 75 74 74" ;;
reggae) curve="71 71 72 81 71 62 62 71 71 71" ;;
rock) curve="58 63 80 84 77 66 58 55 55 55" ;;
ska) curve="75 79 78 72 66 63 58 57 55 57" ;;
soft_rock) curve="66 66 69 72 78 80 77 72 68 58" ;;
soft) curve="65 70 73 75 73 66 59 57 55 53" ;;
techno) curve="60 63 71 80 79 71 60 57 57 58" ;;
*) echo "Unknown profile ${profile}" >&2 ;;
esac

## [ "${curve}" ] && set_equalizer_curve "${curve}"

On 18/06/2015 22:21, jan gloeckner wrote:

> can't find the bash script mixerpreset. do I miss something?!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/v0d0r/volumio-hacks/issues/1#issuecomment-113278684.

## 

Kevin
